'use client';

import { useMemo, useState } from 'react';

import { listings, kbInventory, complexLinks, kbLinks, asilLinks } from './data';
import { trades } from './trades';

const stats = ([2,3,4] as const).map(complex => {
  const rows = listings.filter(item => item.complex === complex);
  return { complex, groups: rows.length, naverAds: rows.reduce((n,i) => n+i.ads,0), kbAds: rows.reduce((n,i) => n+(i.kbAds || 0),0), range: Math.min(...rows.map(i=>i.price))+'–'+Math.max(...rows.map(i=>i.price))+'억' };
});

export default function Home() {
  const [complex, setComplex] = useState<0 | 2 | 3 | 4>(0);
  const [sort, setSort] = useState<'price' | 'building'>('price');
  const visible = useMemo(() => listings.filter((item) => complex === 0 || item.complex === complex).sort((a, b) => sort === 'price' ? a.price - b.price : a.building.localeCompare(b.building, 'ko')), [complex, sort]);

  return <main>
    <header className="masthead"><div className="eyebrow">신봉동 동일하이빌 · 매매 후보 리포트</div><div className="titleRow"><h1>매물 · 시세 · 실거래</h1><div className="stamp"><b>2026.09.06</b><span>포털 확인 기준</span></div></div><p className="lede">네이버·KB·아실의 공개 정보를 비교합니다. 제외 요청한 매물은 전체 목록에서도 삭제했습니다. 표시된 {listings.length}개 비교 묶음은 실제 집 수를 뜻하지 않으며, 포털별 광고 수는 서로 더하지 않습니다.</p></header>
    <section className="stats" aria-label="단지별 요약">{stats.map((s) => <article key={s.complex} className={`statCard c${s.complex}`}><div className="statTop"><span>{s.complex}단지</span><strong>{s.range}</strong></div><div className="portalCounts"><div><b>{s.naverAds}</b><span>표시 네이버 광고</span></div><div><b>{s.kbAds}</b><span>표시 KB 광고</span></div></div><p>제외 처리 후 {s.groups}개 비교 묶음</p><div className="sourceLinks"><a href={complexLinks[s.complex]} target="_blank" rel="noreferrer">네이버 전체 ↗</a><a href={kbLinks[s.complex]} target="_blank" rel="noreferrer">KB부동산 ↗</a><a href={asilLinks[s.complex]} target="_blank" rel="noreferrer">아실 ↗</a></div></article>)}</section>
    <section className="inventory"><div className="sectionHeading"><div><span className="kicker">전체 후보군</span><h2>단지별 매물 비교</h2></div><div className="controls" aria-label="매물 필터">{[0,2,3,4].map((n) => <button key={n} aria-pressed={complex === n} className={complex === n ? 'selected' : ''} onClick={() => setComplex(n as 0|2|3|4)}>{n === 0 ? '전체' : `${n}단지`}</button>)}<select aria-label="정렬" value={sort} onChange={(e) => setSort(e.target.value as 'price'|'building')}><option value="price">낮은 가격순</option><option value="building">동 순서</option></select></div></div>
      <div className="tableWrap"><table><thead><tr><th scope="col">단지·동</th><th scope="col">매매가</th><th scope="col">공급/전용</th><th scope="col">층</th><th scope="col">포털 광고</th><th scope="col">광고 요약</th><th scope="col">원문</th></tr></thead><tbody>{visible.map((item,index) => <tr key={`${item.complex}-${item.building}-${item.price}-${item.floor}-${index}`}><td><span className={`complexDot c${item.complex}`}>{item.complex}</span><b>{item.building}</b></td><td className="price">{item.priceLabel}</td><td>{item.area}</td><td>{item.floor}</td><td><div className="portalBadges"><b>네이버 {item.ads}</b>{item.kbAds !== undefined && <b>KB {item.kbAds}</b>}{item.asilAds && <b>아실 {item.asilAds}</b>}</div></td><td className="note">{item.note}</td><td><div className="tableLinks">{item.links.map((link) => <a key={link.href} href={link.href} target="_blank" rel="noreferrer">{link.label}</a>)}<a href={kbLinks[item.complex]} target="_blank" rel="noreferrer">KB 단지</a></div></td></tr>)}</tbody></table></div>
    </section>
    <section className="kbInventory"><div className="sectionHeading"><div><span className="kicker">KB부동산 추가 확인</span><h2>면적별 KB 시세</h2></div><p>2026.09.04 시세 · 09.06 조회</p></div><div className="tableWrap"><table className="kbTable"><thead><tr><th scope="col">단지</th><th scope="col">공급/전용면적</th><th scope="col">KB 전체 광고</th><th scope="col">KB 일반가</th><th scope="col">KB 시세 범위</th><th scope="col">원문</th></tr></thead><tbody>{kbInventory.map((item) => <tr key={`${item.complex}-${item.area}`}><td><span className={`complexDot c${item.complex}`}>{item.complex}</span><b>{item.complex}단지</b></td><td>{item.area}</td><td><b>{item.listings}건</b></td><td className="price">{item.generalPrice}</td><td>{item.priceBand}{item.note && <small className="inlineNote">{item.note}</small>}</td><td><div className="tableLinks"><a aria-label={`${item.complex}단지 KB부동산 상세`} href={kbLinks[item.complex]} target="_blank" rel="noreferrer">KB 상세</a></div></td></tr>)}</tbody></table></div><p className="sourceNote">KB 전체 집계는 2단지 11건·3단지 11건·4단지 37건(제외 처리 전)으로 위 표시 광고 수와 다릅니다. 일반가는 개별 매물 호가나 실거래가가 아닙니다. 시세 미제공은 0원이 아닙니다.</p></section>
    <section className="kbInventory"><div className="sectionHeading"><div><span className="kicker">아실 · 국토교통부 신고자료 기반</span><h2>최근 매매 실거래 참고</h2></div><p>면적별 확인 사례 · 전체 거래 내역 아님</p></div><div className="tableWrap"><table className="kbTable"><thead><tr><th>계약일</th><th>단지·동</th><th>전용 타입</th><th>층</th><th>실거래가</th><th>비고·원문</th></tr></thead><tbody>{trades.map(t => <tr key={t.complex+'-'+t.date+'-'+t.building+'-'+t.floor}><td>{t.date}</td><td>{t.complex}단지 · {t.building}동</td><td>{t.area}㎡대</td><td>{t.floor}층</td><td className="price">{(t.price/10000).toLocaleString('ko-KR')}억</td><td>{t.note} <a href={asilLinks[t.complex]} target="_blank" rel="noreferrer">아실 ↗</a></td></tr>)}</tbody></table></div><p className="sourceNote">전용 타입은 아실의 정수 표기입니다. 2단지 33평·4단지 62평은 확인된 최근 매매가 오래되어 계약연도를 그대로 표시했습니다. 직거래는 일반 중개거래와 구분했으며, 신고 지연·정정·해제로 내역이 바뀔 수 있습니다.</p></section>
    <aside className="caution"><b>읽는 법</b><p>2026.09.06 네이버 매매 광고 58건, KB 매매 집계 59건과 목록, 아실 실거래 및 4단지 광고 3건을 확인했습니다. 제외 요청 8개 묶음은 삭제했습니다. 동·가격·면적이 같아도 호수 확인 전에는 같은 집으로 확정하지 않습니다. 아실 광고는 중개사·동·가격·층·설명이 일치하는 행에 출처를 추가했습니다. 개발계획 확정 등 광고 주장은 검증된 사실로 옮기지 않았습니다. 매도 가능 여부와 정확한 동호수는 중개사에게 확인하세요.</p></aside>
    <footer><span>신봉마을 동일하이빌 2·3·4단지</span><span>주소 기준: 경기 용인시 수지구 신봉동</span></footer>
  </main>;
}
